// Generated by CoffeeScript 1.4.0
var log, q;

q = function(query) {
  return document.querySelector(query);
};

log = function() {
  return console.log.apply(console, arguments);
};

window.onload = function() {
  var data, mnt;
  mnt = q("#mnt");
  data = {
    "class": "border",
    $: [
      {
        "class": "a",
        $: [
          {
            "": "span",
            _: "inner text"
          }
        ]
      }, {
        "class": "a",
        $: [
          {
            "": "span",
            _: "more text"
          }
        ]
      }
    ]
  };
  log(data);
  return mnt.innerHTML = json2page(data);
};
