// Generated by CoffeeScript 1.4.0
var json2page;

json2page = function(data) {
  var is_arr, is_str, render, render_arr, render_elem;
  is_arr = function(item) {
    return Array.isArray(item);
  };
  is_str = function(item) {
    return (typeof item) === "string";
  };
  render_arr = function(list) {
    return list.map(render_elem).join("");
  };
  render_elem = function(obj) {
    var attr, attr_str, attrbutes, inner, tag_name, value;
    tag_name = "div";
    inner = "";
    attrbutes = [];
    for (attr in obj) {
      value = obj[attr];
      switch (attr) {
        case "":
          tag_name = value;
          break;
        case "$":
          inner = render_arr(value);
          break;
        case "_":
          if (!(inner.length > 0)) {
            inner = value;
          }
          break;
        default:
          attrbutes.push("" + attr + "=\"" + value + "\"");
      }
    }
    attr_str = attrbutes.join(" ");
    return "<" + tag_name + " " + attr_str + ">" + inner + "</" + tag_name + ">";
  };
  render = function(item) {
    if (is_arr(item)) {
      return render_arr(item);
    } else if (is_str(item)) {
      return item;
    } else {
      return render_elem(item);
    }
  };
  return render(data);
};

if (typeof window !== "undefined" && window !== null) {
  window.json2page = json2page;
}

if (typeof exports !== "undefined" && exports !== null) {
  exports.json2page = json2page;
}
